name: coco-py37
dependencies:
  - python=3.7.11
  - pip=21.2.2

  - numpy=1.21.2
  - matplotlib=3.5.0
  # - scipy=1.7.3
  # - pandas=1.3.5

  - tensorflow==1.15

  - pip:
    # - absl-py==0.11.0
    # - kinpy==0.1.0
    - gym==0.21.0
    - scikit-learn
    # - mujoco_py==2.1.2.14
    # - mpi4py